### ISSUE TITLE
CIDs don't match

### ISSUE THREAD

**Issue by hqd2009** [magik6k/git-remote-ipld#1]
When I run git push ipld::, I get an error message:

command push: CIDs don't match: expected z8mWaJY6TH87sXCTgqUribMLnSxLwbAaS, got ""

I check the source code and find the error comes from push.go: 
1) expectedCid = cid.NewCidV1(0x78, mhash)
2) res = api.DagPut(raw, "raw", "git")
3) if expectedCid != res {....}

How to solve this problem? 
Thank you.

**Comment by magik6k** [comment]
Looks like either you are using really outdated IPFS version or something went terribly wrong. Can you try upgrading to 0.4.11 if you are not using it already?

**Comment by hqd2009** [comment]
@magik6k 

Thank you!
But when I upgrade IPFS to 0.4.11, the error still remains.

So I check this error deeply. 
(1) When I use res = api.DagPut(raw, "raw", "git"),
the function DagPut(data interface{}, ienc, kind string) (string, error) returns ("", error)  (this function comes from the file dag.go in github.com/ipfs/go-ipfs-api repo)

resp, err := req.Send(s.httpcli)
if resp.Error != nil {                       //this error happens
	APIPrintFile("resp error")
	return "", resp.Error
}

(2) When I use res = api.DagPut(raw, "raw", "cbor"),
the function DagPut(data interface{}, ienc, kind string) (string, error) works correctly, return  (zdpuAq1uuyyVbMd8NrSpGAqXoS364YkJhp9rBVjomKnyebhJG, nil).
However, res = zdpuAq1uuyyVbMd8NrSpGAqXoS364YkJhp9rBVjomKnyebhJG, expectedCid = z8mWaJY6TH87sXCTgqUribMLnSxLwbAaS, they do not match.

So I think "git" in api.DagPut(raw, "raw", "git") may lead to this error,

**Comment by magik6k** [comment]
Oh, you need to enable git plugin as described in https://github.com/ipfs/go-ipfs/blob/master/docs/plugins.md. I'll update README here to point there. Let me know if it works.

**Comment by hqd2009** [comment]
@magik6k 
Thanks! It works correctly!
