### ISSUE TITLE
Address scheme

### ISSUE THREAD

**Issue by lgierth** [magik6k/git-remote-ipld#3]
Is there a way to make this work with an addressing schema a la `ipfs://<hash>` or `dweb:/ipfs/<hash>`?

Ideally we'd be using the same two schemes everywhere, to minimize UX friction.

**Comment by magik6k** [comment]
`ipfs://<hash>` will be easy to get working, problem with `dweb:/ipfs/<hash>` is that git interprets it as 'clone /ipfs/<hash> from ssh host dweb'.

**Comment by lgierth** [comment]
Hah got it - `ipfs://<hash>` would be awesome then! I wonder if we could also clone from / push to `ipns://`? That'd basically be `ipfs add`+`ipfs name publish`.

**Comment by magik6k** [comment]
IPNS is totally possible, though that would be a separate helper. AFAIK we can't yet link to CIDv1s from IPNS, though we can probably just make an dag-pb object/directory which would link refs(branches/tags/etc) to ipld-git objects

**Comment by lgierth** [comment]
I actually meant ipfs://, not ipld:// ;)

**Comment by magik6k** [comment]
Oh.. I made it a valid prefix too now, though you will need to rename/symlink the binary as `git-remote-ipfs` to make it work.

Thinking about it now, I'll probably use the `ipfs://` for the more advanced helper which will use IPNS and support branches/refs properly.
