### ISSUE TITLE
Make installation instructions more explicit

### ISSUE THREAD

**Issue by leavehouse** [magik6k/git-remote-ipld#5]
The first step in the installation instructions is "goget/clone/download the repo", which is not super helpful, but when this repo was on commit f5a10c1ae01071b6a897f4e21e42e2b8be776714 it was easy to guess that this meant something like

`go get -u -d github.com/magik6k/git-remote-ipld`

However, doing this for the current master results in:

`package github.com/magik6k/git-remote-ipld: no Go files in /home/leavehouse/go/src/github.com/magik6k/git-remote-ipld`

I did manage to get this working by manually `git clone`ing into the appropriate directory in my GOPATH, but perhaps you could explicitly add the command that will download this via `go get`?

**Comment by magik6k** [comment]
Fixed in https://github.com/magik6k/git-remote-ipld/commit/f74fe510174d086b783bdadcdfcadf9786c8ca69
